

/* Interpreter Types at types/interpreter_types.py */



/**
 * Percent Change Interpreter Configuration
 * The configuration used in order to interpret the model's predictions based on the 
 * percentual change from the first to the last prediction.
 */
 export interface IPercentChangeInterpreterConfig {
    min_increase_change: number,
    min_decrease_change: number
}





/**
 * Probability Interpreter Configuration
 * The configuration used in order to interpret the model's predictions based on the 
 * up and down probability.
 */
export interface IProbabilityInterpreterConfig {
    min_increase_probability: number
    min_decrease_probability: number
}




/**
 * Consensus Interpreter Configuration
 * The configuration used in order to interpret the model's predictions based on the 
 * predictions generated by other models.
 */
 export interface IConsensusInterpreterConfig {
    min_consensus: number
}
